---
title: "Homework 6"
output: github_document
---
  
### Econ B2000, MA Econometrics
### Kevin R Foster, the Colin Powell School at the City College of New York, CUNY
### Fall 2022
### Due 8am EST Friday Oct 28, 2022

*Each student should submit a separate assignment, even if it is an identical computer file to the rest of your study group. When submitting assignments, please include your name and the assignment number as part of the filename. Please write the names of your study group members at the beginning of your homework.*


1. What are the names of the people in your lab group?
2. Write up the results of your work in Lab 6. Explain each step. Impress me. Include some predicted values, to best explain some of your interaction effects.
3. Each person in the group should find 2 academic articles related to your current choice of final project. Write a short paragraph on each, concentrating on what data is used (and whether it is accessible), what econometric techniques, and what questions are addressed. Include names of people in your project group (if different from lab group)

